### ISSUE TITLE
Manual or Readme?

### ISSUE THREAD

**Issue by aulinang** [frankhirsch/ioBroker.etamon#4]
Hi Frank,

First of all, many thanks for the adapter.
But how does the adapter work? Have installed in ioBroker, but no new function appears in instances or objects.

Many Thanks
Best regards, Stefan

**Comment by frankhirsch** [comment]
Hi Stefan,
I added the [README](https://github.com/frankhirsch/ioBroker.etamon/blob/master/README.md) - as you will notice I had issues running the code on my NAS device myself, whereas there has been no issue when doing the same on a laptop during the development process. Although I spent many hours trying to find out what goes wrong, unfortunately I do not have the deeper knowledge of debugging iobroker to get into the details. Therefore I recommend using the JS alternative described in the README which works fine without any issues.

Best,
Frank

**Comment by frankhirsch** [comment]
Yes, added...
