### ISSUE TITLE
Adapter aktualisiert keine Werte 

### ISSUE THREAD

**Issue by pschyrembel258** [frankhirsch/ioBroker.etamon#8]
Hallo, ich habe den Adapter unter iobroker installiert, er zeigt mir auch werte an, leider werden diese auch nicht mehr aktualisiert, selbst nach Neustart des Adapters oder von iobroker.

Gruß Daniel

**Comment by frankhirsch** [comment]
Hallo, ich habe bereits in der Vergangenheit festgestellt dass iobroker mit der Masse von Daten die hier aktualisiert werden immer wieder Probleme hatte. Insbesondere wenn iobroker auf etwas schmalbrüstigen Geräten wie einem NAS oder einem Raspberry Pi läuft habe ich das mit dem Adapter leider nicht stabil hinbekommen. Wenn Sie das Plugin verwenden wollen müssten Sie sicherstellen dass die Hardware auf dem iobroker läuft genügend Leistung bietet (hatte während der Entwicklung ohne Probleme auf einem Laptop funktioniert).

Ich werde aber in der Anleitung noch ein Skript einfügen welches den gleichen Zweck erfüllt und stabil funktioniert.

**Comment by frankhirsch** [comment]
Voila - siehe https://github.com/frankhirsch/ioBroker.etamon/blob/master/README.md
Ich hoffe das hilft!

Gruß,
Frank

**Comment by ghost** [comment]
Hallo, 

Ich bräuchte noch ein wenig Hilfe. Ich habe das Skript in ein JS Skript in iobroker kopiert und die IP angepasst. Wenn ich jetzt das Skript starte bekomme ich Fehlermeldungen. Muss ich noch etwas verändern?

Vielen Dank für die Hilfe

Daniel Mehne

**Comment by frankhirsch** [comment]
Eventuell musst Du noch die Module im npm installieren falls nicht vorhanden...

**Comment by ghost** [comment]
Welche Module meinst du?

Von meinem iPhone gesendet
